apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.secretName }}
  namespace:  {{ .Values.api.secretNamespace }}
type: Opaque
data:
  CUSTOMER-APIS-DATASOURCE-PASSWORD: ${CUSTOMER-APIS-DATASOURCE-PASSWORD}